include: package:flutter_lints/flutter.yaml   # start with Flutter’s default set

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false         # allow print() during dev

analyzer:
  errors:
    invalid_annotation_target: ignore
