name: savings_app
description: A modern savings app with Supabase backend

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # ✅ Supabase SDK – single dependency includes auth & postgrest
  supabase_flutter: ^2.5.1

  # ✅ State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # ✅ UI and Fonts
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
